export const MOCK_CATEGORIES = [
  { id: 'fruits', name: 'Buah-buahan', iconUrl: '🍎', colorTheme: '#FF6B6B', borderColor: '#e53e3e' },
  { id: 'animals', name: 'Hewan', iconUrl: '🦁', colorTheme: '#4ECDC4', borderColor: '#319795' },
  { id: 'numbers', name: 'Angka', iconUrl: '1️⃣', colorTheme: '#FFE66D', borderColor: '#d69e2e' },
  { id: 'colors', name: 'Warna', iconUrl: '🎨', colorTheme: '#9F7AEA', borderColor: '#6b46c1' },
  { id: 'activities', name: 'Kegiatan', iconUrl: '🏃', colorTheme: '#63B3ED', borderColor: '#3182CE' },
  { id: 'adjectives', name: 'Sifat & Fisik', iconUrl: '🧑', colorTheme: '#F6E05E', borderColor: '#D69E2E' },
];

export const MOCK_CARDS = {
  'fruits': [
    { id: 1, frontText: 'Apple', backText: 'Apel', imageUrl: '/apple.png', emoji: '🍎', exampleSentence: 'I eat an apple', exampleTranslation: 'Saya makan sebuah apel' },
    { id: 2, frontText: 'Banana', backText: 'Pisang', emoji: '🍌', exampleSentence: 'Monkeys love banana', exampleTranslation: 'Monyet suka pisang' },
    { id: 3, frontText: 'Orange', backText: 'Jeruk', emoji: '🍊', exampleSentence: 'This orange is sweet', exampleTranslation: 'Jeruk ini manis' },
    { id: 4, frontText: 'Grape', backText: 'Anggur', emoji: '🍇', exampleSentence: 'I like purple grapes', exampleTranslation: 'Saya suka anggur ungu' },
    { id: 5, frontText: 'Strawberry', backText: 'Stroberi', emoji: '🍓', exampleSentence: 'The strawberry is red', exampleTranslation: 'Stroberi itu merah' },
    { id: 6, frontText: 'Watermelon', backText: 'Semangka', emoji: '🍉', exampleSentence: 'Watermelon is very big', exampleTranslation: 'Semangka sangat besar' },
    { id: 7, frontText: 'Mango', backText: 'Mangga', emoji: '🥭', exampleSentence: 'Mango is yummy', exampleTranslation: 'Mangga enak sekali' },
    { id: 8, frontText: 'Pineapple', backText: 'Nanas', emoji: '🍍', exampleSentence: 'Pineapple is yellow', exampleTranslation: 'Nanas berwarna kuning' },
    { id: 9, frontText: 'Cherry', backText: 'Ceri', emoji: '🍒', exampleSentence: 'Two small cherries', exampleTranslation: 'Dua ceri kecil' },
    { id: 10, frontText: 'Peach', backText: 'Persik', emoji: '🍑', exampleSentence: 'Peach is soft', exampleTranslation: 'Persik itu lembut' },
  ],
  'animals': [
    { id: 11, frontText: 'Cat', backText: 'Kucing', imageUrl: '/cat.png', emoji: '🐱', exampleSentence: 'The cat sleeps', exampleTranslation: 'Kucing itu tidur' },
    { id: 12, frontText: 'Dog', backText: 'Anjing', emoji: '🐶', exampleSentence: 'The dog barks', exampleTranslation: 'Anjing itu menggonggong' },
    { id: 13, frontText: 'Elephant', backText: 'Gajah', emoji: '🐘', exampleSentence: 'Elephant is very big', exampleTranslation: 'Gajah sangat besar' },
    { id: 14, frontText: 'Lion', backText: 'Singa', emoji: '🦁', exampleSentence: 'Lion is the king', exampleTranslation: 'Singa adalah raja' },
    { id: 15, frontText: 'Tiger', backText: 'Harimau', emoji: '🐯', exampleSentence: 'Tiger can run fast', exampleTranslation: 'Harimau berlari cepat' },
    { id: 16, frontText: 'Monkey', backText: 'Monyet', emoji: '🐒', exampleSentence: 'Monkey likes banana', exampleTranslation: 'Monyet suka pisang' },
    { id: 17, frontText: 'Rabbit', backText: 'Kelinci', emoji: '🐰', exampleSentence: 'Rabbit can jump', exampleTranslation: 'Kelinci bisa melompat' },
    { id: 18, frontText: 'Bear', backText: 'Beruang', emoji: '🐻', exampleSentence: 'Brown bear is sleeping', exampleTranslation: 'Beruang coklat tidur' },
    { id: 19, frontText: 'Giraffe', backText: 'Jerapah', emoji: '🦒', exampleSentence: 'Giraffe is very tall', exampleTranslation: 'Jerapah sangat tinggi' },
    { id: 20, frontText: 'Zebra', backText: 'Zebra', emoji: '🦓', exampleSentence: 'Zebra is black and white', exampleTranslation: 'Zebra hitam dan putih' },
  ],
  'numbers': [
    { id: 21, frontText: 'One', backText: 'Satu', emoji: '1️⃣', exampleSentence: 'I have one apple', exampleTranslation: 'Saya punya satu apel' },
    { id: 22, frontText: 'Two', backText: 'Dua', emoji: '2️⃣', exampleSentence: 'Two cats are playing', exampleTranslation: 'Dua kucing sedang bermain' },
    { id: 23, frontText: 'Three', backText: 'Tiga', emoji: '3️⃣', exampleSentence: 'Three little birds', exampleTranslation: 'Tiga burung kecil' },
    { id: 24, frontText: 'Four', backText: 'Empat', emoji: '4️⃣', exampleSentence: 'Four legs on a dog', exampleTranslation: 'Empat kaki anjing' },
    { id: 25, frontText: 'Five', backText: 'Lima', emoji: '5️⃣', exampleSentence: 'Five fingers on a hand', exampleTranslation: 'Lima jari di tangan' },
    { id: 26, frontText: 'Six', backText: 'Enam', emoji: '6️⃣', exampleSentence: 'I am six years old', exampleTranslation: 'Saya berumur enam tahun' },
    { id: 27, frontText: 'Seven', backText: 'Tujuh', emoji: '7️⃣', exampleSentence: 'Seven days in a week', exampleTranslation: 'Tujuh hari seminggu' },
    { id: 28, frontText: 'Eight', backText: 'Delapan', emoji: '8️⃣', exampleSentence: 'Spider has eight legs', exampleTranslation: 'Laba-laba punya delapan kaki' },
    { id: 29, frontText: 'Nine', backText: 'Sembilan', emoji: '9️⃣', exampleSentence: 'Nine red apples', exampleTranslation: 'Sembilan apel merah' },
    { id: 30, frontText: 'Ten', backText: 'Sepuluh', emoji: '🔟', exampleSentence: 'I have ten toes', exampleTranslation: 'Saya punya sepuluh jari kaki' },
  ],
  'colors': [
    { id: 31, frontText: 'Red', backText: 'Merah', emoji: '🔴', exampleSentence: 'The apple is red', exampleTranslation: 'Apel itu merah' },
    { id: 32, frontText: 'Blue', backText: 'Biru', emoji: '🔵', exampleSentence: 'The sky is blue', exampleTranslation: 'Langit itu biru' },
    { id: 33, frontText: 'Green', backText: 'Hijau', emoji: '🟢', exampleSentence: 'The grass is green', exampleTranslation: 'Rumput itu hijau' },
    { id: 34, frontText: 'Yellow', backText: 'Kuning', emoji: '🟡', exampleSentence: 'The sun is yellow', exampleTranslation: 'Matahari itu kuning' },
    { id: 35, frontText: 'Orange', backText: 'Oranye', emoji: '🟠', exampleSentence: 'The orange is orange', exampleTranslation: 'Jeruk warnanya oranye' },
    { id: 36, frontText: 'Purple', backText: 'Ungu', emoji: '🟣', exampleSentence: 'The grape is purple', exampleTranslation: 'Anggur itu ungu' },
    { id: 37, frontText: 'Pink', backText: 'Merah Muda', emoji: '🌸', exampleSentence: 'The flower is pink', exampleTranslation: 'Bunga itu merah muda' },
    { id: 38, frontText: 'Black', backText: 'Hitam', emoji: '⚫', exampleSentence: 'The cat is black', exampleTranslation: 'Kucing itu hitam' },
    { id: 39, frontText: 'White', backText: 'Putih', emoji: '⚪', exampleSentence: 'The cloud is white', exampleTranslation: 'Awan itu putih' },
    { id: 40, frontText: 'Brown', backText: 'Coklat', emoji: '🟤', exampleSentence: 'The bear is brown', exampleTranslation: 'Beruang itu coklat' },
  ],
  'activities': [
    { id: 41, frontText: 'Wake up', backText: 'Bangun tidur', emoji: '☀️', exampleSentence: 'I wake up early', exampleTranslation: 'Saya bangun pagi' },
    { id: 42, frontText: 'Brush teeth', backText: 'Sikat gigi', emoji: '🪥', exampleSentence: 'I brush my teeth', exampleTranslation: 'Saya sikat gigi' },
    { id: 43, frontText: 'Wash face', backText: 'Cuci muka', emoji: '🧼', exampleSentence: 'I wash my face', exampleTranslation: 'Saya mencuci muka' },
    { id: 44, frontText: 'Take a shower', backText: 'Mandi', emoji: '🚿', exampleSentence: 'I take a shower', exampleTranslation: 'Saya mandi' },
    { id: 45, frontText: 'Get dressed', backText: 'Berpakaian', emoji: '👕', exampleSentence: 'I get dressed fast', exampleTranslation: 'Saya berpakaian cepat' },
    { id: 46, frontText: 'Comb hair', backText: 'Menyisir rambut', emoji: '💈', exampleSentence: 'I comb my hair', exampleTranslation: 'Saya menyisir rambut saya' },
    { id: 47, frontText: 'Eat breakfast', backText: 'Sarapan', emoji: '🥞', exampleSentence: 'I eat breakfast daily', exampleTranslation: 'Saya sarapan setiap hari' },
    { id: 48, frontText: 'Drink water', backText: 'Minum air', emoji: '💧', exampleSentence: 'I drink fresh water', exampleTranslation: 'Saya minum air segar' },
    { id: 49, frontText: 'Drink milk', backText: 'Minum susu', emoji: '🥛', exampleSentence: 'I drink cold milk', exampleTranslation: 'Saya minum susu dingin' },
    { id: 50, frontText: 'Pack bag', backText: 'Menyiapkan tas', emoji: '🎒', exampleSentence: 'I pack my bag', exampleTranslation: 'Saya menyiapkan tas saya' },
    { id: 51, frontText: 'Wear shoes', backText: 'Memakai sepatu', emoji: '👟', exampleSentence: 'I wear blue shoes', exampleTranslation: 'Saya memakai sepatu biru' },
    { id: 52, frontText: 'Go to school', backText: 'Pergi ke sekolah', emoji: '🏫', exampleSentence: 'I go to school', exampleTranslation: 'Saya pergi ke sekolah' },
    { id: 53, frontText: 'Ride a bus', backText: 'Naik bus', emoji: '🚌', exampleSentence: 'I ride a bus', exampleTranslation: 'Saya naik bus' },
    { id: 54, frontText: 'Say goodbye', backText: 'Mengucapkan selamat tinggal', emoji: '👋', exampleSentence: 'I say goodbye mom', exampleTranslation: 'Saya ucapkan selamat tinggal ibu' },
    { id: 55, frontText: 'Meet friends', backText: 'Bertemu teman', emoji: '👫', exampleSentence: 'I meet my friends', exampleTranslation: 'Saya bertemu teman-teman saya' },
    { id: 56, frontText: 'Greet teacher', backText: 'Menyapa guru', emoji: '👩‍🏫', exampleSentence: 'I greet my teacher', exampleTranslation: 'Saya menyapa guru saya' },
    { id: 57, frontText: 'Sit down', backText: 'Duduk', emoji: '🪑', exampleSentence: 'I sit down here', exampleTranslation: 'Saya duduk di sini' },
    { id: 58, frontText: 'Open book', backText: 'Membuka buku', emoji: '📖', exampleSentence: 'I open my book', exampleTranslation: 'Saya membuka buku saya' },
    { id: 59, frontText: 'Read book', backText: 'Membaca buku', emoji: '📚', exampleSentence: 'I read a book', exampleTranslation: 'Saya membaca sebuah buku' },
    { id: 60, frontText: 'Write', backText: 'Menulis', emoji: '✏️', exampleSentence: 'I write my name', exampleTranslation: 'Saya menulis nama saya' },
    { id: 61, frontText: 'Draw', backText: 'Menggambar', emoji: '🎨', exampleSentence: 'I draw an apple', exampleTranslation: 'Saya menggambar apel' },
    { id: 62, frontText: 'Color', backText: 'Mewarnai', emoji: '🖍️', exampleSentence: 'I color the sun', exampleTranslation: 'Saya mewarnai matahari' },
    { id: 63, frontText: 'Raise hand', backText: 'Angkat tangan', emoji: '🙋', exampleSentence: 'I raise my hand', exampleTranslation: 'Saya mengangkat tangan saya' },
    { id: 64, frontText: 'Answer', backText: 'Menjawab', emoji: '💬', exampleSentence: 'I answer the question', exampleTranslation: 'Saya menjawab pertanyaannya' },
    { id: 65, frontText: 'Ask question', backText: 'Bertanya', emoji: '❓', exampleSentence: 'I ask a question', exampleTranslation: 'Saya menanyakan sebuah pertanyaan' },
    { id: 66, frontText: 'Listen', backText: 'Mendengarkan', emoji: '👂', exampleSentence: 'I listen to you', exampleTranslation: 'Saya mendengarkanmu' },
    { id: 67, frontText: 'Sing', backText: 'Bernyanyi', emoji: '🎵', exampleSentence: 'I sing a song', exampleTranslation: 'Saya menyanyikan sebuah lagu' },
    { id: 68, frontText: 'Dance', backText: 'Menari', emoji: '💃', exampleSentence: 'I dance with joy', exampleTranslation: 'Saya menari dengan gembira' },
    { id: 69, frontText: 'Play outside', backText: 'Bermain di luar', emoji: '⚽', exampleSentence: 'I play outside now', exampleTranslation: 'Saya bermain di luar sekarang' },
    { id: 70, frontText: 'Run', backText: 'Berlari', emoji: '🏃', exampleSentence: 'I run very fast', exampleTranslation: 'Saya berlari sangat cepat' },
    { id: 71, frontText: 'Jump', backText: 'Melompat', emoji: '🦘', exampleSentence: 'I jump very high', exampleTranslation: 'Saya melompat sangat tinggi' },
    { id: 72, frontText: 'Eat lunch', backText: 'Makan siang', emoji: '🍱', exampleSentence: 'I eat my lunch', exampleTranslation: 'Saya memakan makan siang saya' },
    { id: 73, frontText: 'Wash hands', backText: 'Mencuci tangan', emoji: '🧴', exampleSentence: 'I wash my hands', exampleTranslation: 'Saya mencuci tangan saya' },
    { id: 74, frontText: 'Share toys', backText: 'Berbagi mainan', emoji: '🧸', exampleSentence: 'I share my toys', exampleTranslation: 'Saya berbagi mainan saya' },
    { id: 75, frontText: 'Help friend', backText: 'Membantu teman', emoji: '🤝', exampleSentence: 'I help my friend', exampleTranslation: 'Saya membantu teman saya' },
    { id: 76, frontText: 'Clean up', backText: 'Membersihkan', emoji: '🧹', exampleSentence: 'I clean up toys', exampleTranslation: 'Saya membereskan mainan' },
    { id: 77, frontText: 'Throw trash', backText: 'Membuang sampah', emoji: '🗑️', exampleSentence: 'I throw the trash', exampleTranslation: 'Saya membuang sampah' },
    { id: 78, frontText: 'Say thanks', backText: 'Mengucapkan terima kasih', emoji: '🙏', exampleSentence: 'I always say thanks', exampleTranslation: 'Saya selalu mengucapkan terima kasih' },
    { id: 79, frontText: 'Say please', backText: 'Mengucapkan tolong', emoji: '🥺', exampleSentence: 'I always say please', exampleTranslation: 'Saya selalu bilang tolong' },
    { id: 80, frontText: 'Go home', backText: 'Pulang ke rumah', emoji: '🏡', exampleSentence: 'I go home now', exampleTranslation: 'Saya pulang ke rumah sekarang' },
    { id: 81, frontText: 'Take off shoes', backText: 'Melepas sepatu', emoji: '👞', exampleSentence: 'I take off shoes', exampleTranslation: 'Saya melepas sepatu' },
    { id: 82, frontText: 'Change clothes', backText: 'Ganti baju', emoji: '👖', exampleSentence: 'I change my clothes', exampleTranslation: 'Saya mengganti pakaian saya' },
    { id: 83, frontText: 'Wash feet', backText: 'Cuci kaki', emoji: '🦶', exampleSentence: 'I wash my feet', exampleTranslation: 'Saya mencuci kaki saya' },
    { id: 84, frontText: 'Rest', backText: 'Istirahat', emoji: '🛋️', exampleSentence: 'I rest for awhile', exampleTranslation: 'Saya beristirahat sejenak' },
    { id: 85, frontText: 'Take a nap', backText: 'Tidur siang', emoji: '😴', exampleSentence: 'I take a nap', exampleTranslation: 'Saya tidur siang' },
    { id: 86, frontText: 'Wake up nap', backText: 'Bangun tidur siang', emoji: '🥱', exampleSentence: 'I wake up now', exampleTranslation: 'Saya bangun sekarang' },
    { id: 87, frontText: 'Eat a snack', backText: 'Makan camilan', emoji: '🍪', exampleSentence: 'I eat a snack', exampleTranslation: 'Saya memakan camilan' },
    { id: 88, frontText: 'Watch TV', backText: 'Menonton TV', emoji: '📺', exampleSentence: 'I watch fun TV', exampleTranslation: 'Saya menonton TV yang seru' },
    { id: 89, frontText: 'Play games', backText: 'Bermain game', emoji: '🎮', exampleSentence: 'I play video games', exampleTranslation: 'Saya bermain video game' },
    { id: 90, frontText: 'Read story', backText: 'Membaca cerita', emoji: '🦸', exampleSentence: 'I read a story', exampleTranslation: 'Saya membaca cerita' },
    { id: 91, frontText: 'Ride bike', backText: 'Naik sepeda', emoji: '🚲', exampleSentence: 'I ride my bike', exampleTranslation: 'Saya mengendarai sepeda saya' },
    { id: 92, frontText: 'Play in park', backText: 'Bermain di taman', emoji: '🏞️', exampleSentence: 'I play in park', exampleTranslation: 'Saya bermain di taman' },
    { id: 93, frontText: 'Play with pet', backText: 'Bermain dengan hewan peliharaan', emoji: '🐕', exampleSentence: 'I play with dog', exampleTranslation: 'Saya bermain dengan anjing' },
    { id: 94, frontText: 'Feed the dog', backText: 'Memberi makan anjing', emoji: '🍖', exampleSentence: 'I feed the dog', exampleTranslation: 'Saya memberi makan anjing' },
    { id: 95, frontText: 'Feed the cat', backText: 'Memberi makan kucing', emoji: '🐟', exampleSentence: 'I feed the cat', exampleTranslation: 'Saya memberi makan kucing' },
    { id: 96, frontText: 'Water plants', backText: 'Menyiram tanaman', emoji: '🌱', exampleSentence: 'I water the plants', exampleTranslation: 'Saya menyiram tanaman' },
    { id: 97, frontText: 'Sweep floor', backText: 'Menyapu lantai', emoji: '🧹', exampleSentence: 'I sweep the floor', exampleTranslation: 'Saya menyapu lantai' },
    { id: 98, frontText: 'Help mom', backText: 'Membantu ibu', emoji: '👩‍👦', exampleSentence: 'I help my mom', exampleTranslation: 'Saya membantu ibu saya' },
    { id: 99, frontText: 'Help dad', backText: 'Membantu ayah', emoji: '👨‍👦', exampleSentence: 'I help my dad', exampleTranslation: 'Saya membantu ayah saya' },
    { id: 100, frontText: 'Do homework', backText: 'Mengerjakan PR', emoji: '📝', exampleSentence: 'I do my homework', exampleTranslation: 'Saya mengerjakan PR saya' },
    { id: 101, frontText: 'Study math', backText: 'Belajar matematika', emoji: '➕', exampleSentence: 'I study math today', exampleTranslation: 'Saya belajar matematika hari ini' },
    { id: 102, frontText: 'Study science', backText: 'Belajar sains', emoji: '🔬', exampleSentence: 'I study science today', exampleTranslation: 'Saya belajar sains hari ini' },
    { id: 103, frontText: 'Learn English', backText: 'Belajar bahasa Inggris', emoji: '🔤', exampleSentence: 'I learn English fast', exampleTranslation: 'Saya belajar bahasa Inggris dengan cepat' },
    { id: 104, frontText: 'Play piano', backText: 'Bermain piano', emoji: '🎹', exampleSentence: 'I play the piano', exampleTranslation: 'Saya bermain piano' },
    { id: 105, frontText: 'Play guitar', backText: 'Bermain gitar', emoji: '🎸', exampleSentence: 'I play the guitar', exampleTranslation: 'Saya bermain gitar' },
    { id: 106, frontText: 'Listen music', backText: 'Mendengarkan musik', emoji: '🎧', exampleSentence: 'I listen to music', exampleTranslation: 'Saya mendengarkan musik' },
    { id: 107, frontText: 'Exercise', backText: 'Olahraga', emoji: '💪', exampleSentence: 'I exercise every day', exampleTranslation: 'Saya berolahraga setiap hari' },
    { id: 108, frontText: 'Swim', backText: 'Berenang', emoji: '🏊', exampleSentence: 'I swim in pool', exampleTranslation: 'Saya berenang di kolam' },
    { id: 109, frontText: 'Play football', backText: 'Bermain sepak bola', emoji: '⚽', exampleSentence: 'I play football well', exampleTranslation: 'Saya bermain sepak bola dengan baik' },
    { id: 110, frontText: 'Play basketball', backText: 'Bermain bola basket', emoji: '🏀', exampleSentence: 'I play basketball well', exampleTranslation: 'Saya bermain bola basket dengan baik' },
    { id: 111, frontText: 'Eat dinner', backText: 'Makan malam', emoji: '🍲', exampleSentence: 'I eat my dinner', exampleTranslation: 'Saya makan malam' },
    { id: 112, frontText: 'Drink juice', backText: 'Minum jus', emoji: '🧃', exampleSentence: 'I drink orange juice', exampleTranslation: 'Saya minum jus jeruk' },
    { id: 113, frontText: 'Wash dishes', backText: 'Mencuci piring', emoji: '🍽️', exampleSentence: 'I wash the dishes', exampleTranslation: 'Saya mencuci piring' },
    { id: 114, frontText: 'Wipe table', backText: 'Mengelap meja', emoji: '🧽', exampleSentence: 'I wipe the table', exampleTranslation: 'Saya mengelap meja' },
    { id: 115, frontText: 'Take out trash', backText: 'Membuang sampah', emoji: '🗑️', exampleSentence: 'I take out trash', exampleTranslation: 'Saya membuang sampah' },
    { id: 116, frontText: 'Brush hair', backText: 'Menyisir rambut', emoji: '💇', exampleSentence: 'I brush my hair', exampleTranslation: 'Saya menyisir rambut' },
    { id: 117, frontText: 'Take a bath', backText: 'Mandi rendam', emoji: '🛀', exampleSentence: 'I take a bath', exampleTranslation: 'Saya mandi berendam' },
    { id: 118, frontText: 'Dry hair', backText: 'Mengeringkan rambut', emoji: '🧖', exampleSentence: 'I dry my hair', exampleTranslation: 'Saya mengeringkan rambut saya' },
    { id: 119, frontText: 'Wear pajamas', backText: 'Memakai piyama', emoji: '👘', exampleSentence: 'I wear my pajamas', exampleTranslation: 'Saya memakai piyama saya' },
    { id: 120, frontText: 'Look at moon', backText: 'Melihat bulan', emoji: '🌕', exampleSentence: 'I look at moon', exampleTranslation: 'Saya melihat bulan' },
    { id: 121, frontText: 'Look at stars', backText: 'Melihat bintang', emoji: '⭐', exampleSentence: 'I see the stars', exampleTranslation: 'Saya melihat bintang' },
    { id: 122, frontText: 'Close window', backText: 'Menutup jendela', emoji: '🪟', exampleSentence: 'I close the window', exampleTranslation: 'Saya menutup jendela' },
    { id: 123, frontText: 'Turn off lights', backText: 'Mematikan lampu', emoji: '💡', exampleSentence: 'I turn off lights', exampleTranslation: 'Saya mematikan lampu' },
    { id: 124, frontText: 'Say goodnight', backText: 'Mengucapkan selamat malam', emoji: '🌛', exampleSentence: 'I say goodnight now', exampleTranslation: 'Saya mengucapkan selamat malam sekarang' },
    { id: 125, frontText: 'Hug mom', backText: 'Memeluk ibu', emoji: '🤗', exampleSentence: 'I hug my mom', exampleTranslation: 'Saya memeluk ibu saya' },
    { id: 126, frontText: 'Kiss dad', backText: 'Mencium ayah', emoji: '💋', exampleSentence: 'I kiss my dad', exampleTranslation: 'Saya mencium ayah saya' },
    { id: 127, frontText: 'Go to bed', backText: 'Pergi tidur', emoji: '🛏️', exampleSentence: 'I go to bed', exampleTranslation: 'Saya pergi tidur' },
    { id: 128, frontText: 'Sleep', backText: 'Tidur', emoji: '💤', exampleSentence: 'I sleep very well', exampleTranslation: 'Saya tidur sangat lelap' },
    { id: 129, frontText: 'Dream', backText: 'Bermimpi', emoji: '💭', exampleSentence: 'I have a dream', exampleTranslation: 'Saya mempunyai mimpi' },
    { id: 130, frontText: 'Make bed', backText: 'Merapikan tempat tidur', emoji: '🛌', exampleSentence: 'I make my bed', exampleTranslation: 'Saya merapikan tempat tidur saya' },
    { id: 131, frontText: 'Check time', backText: 'Mengecek waktu', emoji: '⌚', exampleSentence: 'I check the time', exampleTranslation: 'Saya mengecek waktu' },
    { id: 132, frontText: 'Wait for bus', backText: 'Menunggu bus', emoji: '🚏', exampleSentence: 'I wait for bus', exampleTranslation: 'Saya menunggu bus' },
    { id: 133, frontText: 'Cross street', backText: 'Menyeberang jalan', emoji: '🚶', exampleSentence: 'I cross the street', exampleTranslation: 'Saya menyeberang jalan' },
    { id: 134, frontText: 'Look left', backText: 'Menengok kiri', emoji: '👀', exampleSentence: 'I look left now', exampleTranslation: 'Saya menengok kiri sekarang' },
    { id: 135, frontText: 'Use toilet', backText: 'Menggunakan toilet', emoji: '🚽', exampleSentence: 'I use the toilet', exampleTranslation: 'Saya menggunakan toilet' },
    { id: 136, frontText: 'Flush toilet', backText: 'Menyiram toilet', emoji: '🚽', exampleSentence: 'I flush the toilet', exampleTranslation: 'Saya menyiram toilet' },
    { id: 137, frontText: 'Tie shoelaces', backText: 'Mengikat tali sepatu', emoji: '👟', exampleSentence: 'I tie my shoelaces', exampleTranslation: 'Saya mengikat tali sepatu saya' },
    { id: 138, frontText: 'Button shirt', backText: 'Mengkancingkan kemeja', emoji: '👔', exampleSentence: 'I button my shirt', exampleTranslation: 'Saya mengkancingkan kemeja saya' },
    { id: 139, frontText: 'Zip jacket', backText: 'Meresleting jaket', emoji: '🧥', exampleSentence: 'I zip my jacket', exampleTranslation: 'Saya meresleting jaket saya' },
    { id: 140, frontText: 'Put on hat', backText: 'Memakai topi', emoji: '🧢', exampleSentence: 'I put on hat', exampleTranslation: 'Saya memakai topi' }
  ],
  'adjectives': [
    { id: 141, frontText: 'Tall', backText: 'Tinggi', imageUrl: '/adjectives/tall.png', exampleSentence: 'He is very tall', exampleTranslation: 'Dia sangat tinggi' },
    { id: 142, frontText: 'Short', backText: 'Pendek', imageUrl: '/adjectives/short.png', exampleSentence: 'The boy is short', exampleTranslation: 'Anak laki-laki itu pendek' },
    { id: 143, frontText: 'Funny', backText: 'Lucu', imageUrl: '/adjectives/funny.png', exampleSentence: 'The clown is funny', exampleTranslation: 'Badut itu lucu' },
    { id: 144, frontText: 'Kind', backText: 'Baik hati', imageUrl: '/adjectives/kind.png', exampleSentence: 'She is a kind girl', exampleTranslation: 'Dia adalah gadis yang baik hati' },
    { id: 145, frontText: 'Strong', backText: 'Kuat', imageUrl: '/adjectives/strong.png', exampleSentence: 'The man is strong', exampleTranslation: 'Pria itu kuat' },
    { id: 146, frontText: 'Weak', backText: 'Lemah', imageUrl: '/adjectives/weak.png', exampleSentence: 'The bird is weak', exampleTranslation: 'Burung itu lemah' },
    { id: 147, frontText: 'Smart', backText: 'Pintar', imageUrl: '/adjectives/smart.png', exampleSentence: 'She is very smart', exampleTranslation: 'Dia sangat pintar' },
    { id: 148, frontText: 'Silly', backText: 'Konyol', imageUrl: '/adjectives/silly.png', exampleSentence: 'He is acting silly', exampleTranslation: 'Dia bertingkah konyol' },
    { id: 149, frontText: 'Brave', backText: 'Berani', imageUrl: '/adjectives/brave.png', exampleSentence: 'The hero is brave', exampleTranslation: 'Pahlawan itu berani' },
    { id: 150, frontText: 'Shy', backText: 'Pemalu', imageUrl: '/adjectives/shy.png', exampleSentence: 'The little girl is shy', exampleTranslation: 'Gadis kecil itu pemalu' },
    { id: 151, frontText: 'Lazy', backText: 'Malas', imageUrl: '/adjectives/lazy.png', exampleSentence: 'The cat is lazy', exampleTranslation: 'Kucing itu malas' },
    { id: 152, frontText: 'Diligent', backText: 'Rajin', imageUrl: '/adjectives/diligent.png', exampleSentence: 'The student is diligent', exampleTranslation: 'Murid itu rajin' },
    { id: 153, frontText: 'Beautiful', backText: 'Cantik', imageUrl: '/adjectives/beautiful.png', exampleSentence: 'The princess is beautiful', exampleTranslation: 'Putri itu cantik' },
    { id: 154, frontText: 'Handsome', backText: 'Tampan', imageUrl: '/adjectives/handsome.png', exampleSentence: 'The prince is handsome', exampleTranslation: 'Pangeran itu tampan' },
    { id: 155, frontText: 'Cute', backText: 'Imut', imageUrl: '/adjectives/cute.png', exampleSentence: 'The baby is cute', exampleTranslation: 'Bayi itu imut' },
    { id: 156, frontText: 'Fat', backText: 'Gemuk', imageUrl: '/adjectives/fat.png', exampleSentence: 'The bear is fat', exampleTranslation: 'Beruang itu gemuk' },
    { id: 157, frontText: 'Thin', backText: 'Kurus', imageUrl: '/adjectives/thin.png', exampleSentence: 'The stick is thin', exampleTranslation: 'Tongkat itu kurus' },
    { id: 158, frontText: 'Old', backText: 'Tua', imageUrl: '/adjectives/old.png', exampleSentence: 'My grandfather is old', exampleTranslation: 'Kakek saya sudah tua' },
    { id: 159, frontText: 'Young', backText: 'Muda', imageUrl: '/adjectives/young.png', exampleSentence: 'The boy is young', exampleTranslation: 'Anak laki-laki itu muda' },
    { id: 160, frontText: 'Happy', backText: 'Bahagia', imageUrl: '/adjectives/happy.png', exampleSentence: 'I am very happy', exampleTranslation: 'Saya sangat bahagia' },
    { id: 161, frontText: 'Sad', backText: 'Sedih', imageUrl: '/adjectives/sad.png', exampleSentence: 'The girl is sad', exampleTranslation: 'Gadis itu sedih' },
    { id: 162, frontText: 'Angry', backText: 'Marah', imageUrl: '/adjectives/angry.png', exampleSentence: 'The dog is angry', exampleTranslation: 'Anjing itu marah' },
    { id: 163, frontText: 'Calm', backText: 'Tenang', imageUrl: '/adjectives/calm.png', exampleSentence: 'The water is calm', exampleTranslation: 'Airnya tenang' },
    { id: 164, frontText: 'Polite', backText: 'Sopan', imageUrl: '/adjectives/polite.png', exampleSentence: 'He is a polite boy', exampleTranslation: 'Dia adalah anak yang sopan' },
    { id: 165, frontText: 'Tired', backText: 'Lelah', imageUrl: '/adjectives/tired.png', exampleSentence: 'I am tired today', exampleTranslation: 'Saya lelah hari ini' }
  ]
};
