-- ==========================================
-- SUPABASE INITIALIZATION SQL SCRIPT
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    "iconUrl" TEXT,
    "colorTheme" TEXT,
    "borderColor" TEXT
);

-- 2. Create Flashcards Table
CREATE TABLE IF NOT EXISTS flashcards (
    id SERIAL PRIMARY KEY,
    category_id TEXT REFERENCES categories(id),
    "frontText" TEXT NOT NULL,
    "backText" TEXT NOT NULL,
    emoji TEXT,
    "imageUrl" TEXT,
    "audioUrl" TEXT,
    "exampleSentence" TEXT,
    "exampleTranslation" TEXT
);

-- 3. Insert Categories
INSERT INTO categories (id, name, "iconUrl", "colorTheme", "borderColor") VALUES
('fruits', 'Buah-buahan', '🍎', '#FF6B6B', '#e53e3e'),
('animals', 'Hewan', '🦁', '#4ECDC4', '#319795'),
('numbers', 'Angka', '1️⃣', '#FFE66D', '#d69e2e'),
('colors', 'Warna', '🎨', '#9F7AEA', '#6b46c1'),
('activities', 'Kegiatan', '🏃', '#63B3ED', '#3182CE') ON CONFLICT (id) DO NOTHING;

-- 4. Insert Flashcards
INSERT INTO flashcards (category_id, "frontText", "backText", emoji, "imageUrl", "exampleSentence", "exampleTranslation") VALUES
('fruits', 'Apple', 'Apel', '🍎', '/apple.png', 'I eat an apple', 'Saya makan sebuah apel'),
('fruits', 'Banana', 'Pisang', '🍌', NULL, 'Monkeys love banana', 'Monyet suka pisang'),
('fruits', 'Orange', 'Jeruk', '🍊', NULL, 'This orange is sweet', 'Jeruk ini manis'),
('fruits', 'Grape', 'Anggur', '🍇', NULL, 'I like purple grapes', 'Saya suka anggur ungu'),
('fruits', 'Strawberry', 'Stroberi', '🍓', NULL, 'The strawberry is red', 'Stroberi itu merah'),
('fruits', 'Watermelon', 'Semangka', '🍉', NULL, 'Watermelon is very big', 'Semangka sangat besar'),
('fruits', 'Mango', 'Mangga', '🥭', NULL, 'Mango is yummy', 'Mangga enak sekali'),
('fruits', 'Pineapple', 'Nanas', '🍍', NULL, 'Pineapple is yellow', 'Nanas berwarna kuning'),
('fruits', 'Cherry', 'Ceri', '🍒', NULL, 'Two small cherries', 'Dua ceri kecil'),
('fruits', 'Peach', 'Persik', '🍑', NULL, 'Peach is soft', 'Persik itu lembut'),
('animals', 'Cat', 'Kucing', '🐱', '/cat.png', 'The cat sleeps', 'Kucing itu tidur'),
('animals', 'Dog', 'Anjing', '🐶', NULL, 'The dog barks', 'Anjing itu menggonggong'),
('animals', 'Elephant', 'Gajah', '🐘', NULL, 'Elephant is very big', 'Gajah sangat besar'),
('animals', 'Lion', 'Singa', '🦁', NULL, 'Lion is the king', 'Singa adalah raja'),
('animals', 'Tiger', 'Harimau', '🐯', NULL, 'Tiger can run fast', 'Harimau berlari cepat'),
('animals', 'Monkey', 'Monyet', '🐒', NULL, 'Monkey likes banana', 'Monyet suka pisang'),
('animals', 'Rabbit', 'Kelinci', '🐰', NULL, 'Rabbit can jump', 'Kelinci bisa melompat'),
('animals', 'Bear', 'Beruang', '🐻', NULL, 'Brown bear is sleeping', 'Beruang coklat tidur'),
('animals', 'Giraffe', 'Jerapah', '🦒', NULL, 'Giraffe is very tall', 'Jerapah sangat tinggi'),
('animals', 'Zebra', 'Zebra', '🦓', NULL, 'Zebra is black and white', 'Zebra hitam dan putih'),
('numbers', 'One', 'Satu', '1️⃣', NULL, 'I have one apple', 'Saya punya satu apel'),
('numbers', 'Two', 'Dua', '2️⃣', NULL, 'Two cats are playing', 'Dua kucing sedang bermain'),
('numbers', 'Three', 'Tiga', '3️⃣', NULL, 'Three little birds', 'Tiga burung kecil'),
('numbers', 'Four', 'Empat', '4️⃣', NULL, 'Four legs on a dog', 'Empat kaki anjing'),
('numbers', 'Five', 'Lima', '5️⃣', NULL, 'Five fingers on a hand', 'Lima jari di tangan'),
('numbers', 'Six', 'Enam', '6️⃣', NULL, 'I am six years old', 'Saya berumur enam tahun'),
('numbers', 'Seven', 'Tujuh', '7️⃣', NULL, 'Seven days in a week', 'Tujuh hari seminggu'),
('numbers', 'Eight', 'Delapan', '8️⃣', NULL, 'Spider has eight legs', 'Laba-laba punya delapan kaki'),
('numbers', 'Nine', 'Sembilan', '9️⃣', NULL, 'Nine red apples', 'Sembilan apel merah'),
('numbers', 'Ten', 'Sepuluh', '🔟', NULL, 'I have ten toes', 'Saya punya sepuluh jari kaki'),
('colors', 'Red', 'Merah', '🔴', NULL, 'The apple is red', 'Apel itu merah'),
('colors', 'Blue', 'Biru', '🔵', NULL, 'The sky is blue', 'Langit itu biru'),
('colors', 'Green', 'Hijau', '🟢', NULL, 'The grass is green', 'Rumput itu hijau'),
('colors', 'Yellow', 'Kuning', '🟡', NULL, 'The sun is yellow', 'Matahari itu kuning'),
('colors', 'Orange', 'Oranye', '🟠', NULL, 'The orange is orange', 'Jeruk warnanya oranye'),
('colors', 'Purple', 'Ungu', '🟣', NULL, 'The grape is purple', 'Anggur itu ungu'),
('colors', 'Pink', 'Merah Muda', '🌸', NULL, 'The flower is pink', 'Bunga itu merah muda'),
('colors', 'Black', 'Hitam', '⚫', NULL, 'The cat is black', 'Kucing itu hitam'),
('colors', 'White', 'Putih', '⚪', NULL, 'The cloud is white', 'Awan itu putih'),
('colors', 'Brown', 'Coklat', '🟤', NULL, 'The bear is brown', 'Beruang itu coklat'),
('activities', 'Wake up', 'Bangun tidur', '☀️', NULL, 'I wake up early', 'Saya bangun pagi'),
('activities', 'Brush teeth', 'Sikat gigi', '🪥', NULL, 'I brush my teeth', 'Saya sikat gigi'),
('activities', 'Wash face', 'Cuci muka', '🧼', NULL, 'I wash my face', 'Saya mencuci muka'),
('activities', 'Take a shower', 'Mandi', '🚿', NULL, 'I take a shower', 'Saya mandi'),
('activities', 'Get dressed', 'Berpakaian', '👕', NULL, 'I get dressed fast', 'Saya berpakaian cepat'),
('activities', 'Comb hair', 'Menyisir rambut', '💈', NULL, 'I comb my hair', 'Saya menyisir rambut saya'),
('activities', 'Eat breakfast', 'Sarapan', '🥞', NULL, 'I eat breakfast daily', 'Saya sarapan setiap hari'),
('activities', 'Drink water', 'Minum air', '💧', NULL, 'I drink fresh water', 'Saya minum air segar'),
('activities', 'Drink milk', 'Minum susu', '🥛', NULL, 'I drink cold milk', 'Saya minum susu dingin'),
('activities', 'Pack bag', 'Menyiapkan tas', '🎒', NULL, 'I pack my bag', 'Saya menyiapkan tas saya'),
('activities', 'Wear shoes', 'Memakai sepatu', '👟', NULL, 'I wear blue shoes', 'Saya memakai sepatu biru'),
('activities', 'Go to school', 'Pergi ke sekolah', '🏫', NULL, 'I go to school', 'Saya pergi ke sekolah'),
('activities', 'Ride a bus', 'Naik bus', '🚌', NULL, 'I ride a bus', 'Saya naik bus'),
('activities', 'Say goodbye', 'Mengucapkan selamat tinggal', '👋', NULL, 'I say goodbye mom', 'Saya ucapkan selamat tinggal ibu'),
('activities', 'Meet friends', 'Bertemu teman', '👫', NULL, 'I meet my friends', 'Saya bertemu teman-teman saya'),
('activities', 'Greet teacher', 'Menyapa guru', '👩‍🏫', NULL, 'I greet my teacher', 'Saya menyapa guru saya'),
('activities', 'Sit down', 'Duduk', '🪑', NULL, 'I sit down here', 'Saya duduk di sini'),
('activities', 'Open book', 'Membuka buku', '📖', NULL, 'I open my book', 'Saya membuka buku saya'),
('activities', 'Read book', 'Membaca buku', '📚', NULL, 'I read a book', 'Saya membaca sebuah buku'),
('activities', 'Write', 'Menulis', '✏️', NULL, 'I write my name', 'Saya menulis nama saya'),
('activities', 'Draw', 'Menggambar', '🎨', NULL, 'I draw an apple', 'Saya menggambar apel'),
('activities', 'Color', 'Mewarnai', '🖍️', NULL, 'I color the sun', 'Saya mewarnai matahari'),
('activities', 'Raise hand', 'Angkat tangan', '🙋', NULL, 'I raise my hand', 'Saya mengangkat tangan saya'),
('activities', 'Answer', 'Menjawab', '💬', NULL, 'I answer the question', 'Saya menjawab pertanyaannya'),
('activities', 'Ask question', 'Bertanya', '❓', NULL, 'I ask a question', 'Saya menanyakan sebuah pertanyaan'),
('activities', 'Listen', 'Mendengarkan', '👂', NULL, 'I listen to you', 'Saya mendengarkanmu'),
('activities', 'Sing', 'Bernyanyi', '🎵', NULL, 'I sing a song', 'Saya menyanyikan sebuah lagu'),
('activities', 'Dance', 'Menari', '💃', NULL, 'I dance with joy', 'Saya menari dengan gembira'),
('activities', 'Play outside', 'Bermain di luar', '⚽', NULL, 'I play outside now', 'Saya bermain di luar sekarang'),
('activities', 'Run', 'Berlari', '🏃', NULL, 'I run very fast', 'Saya berlari sangat cepat'),
('activities', 'Jump', 'Melompat', '🦘', NULL, 'I jump very high', 'Saya melompat sangat tinggi'),
('activities', 'Eat lunch', 'Makan siang', '🍱', NULL, 'I eat my lunch', 'Saya memakan makan siang saya'),
('activities', 'Wash hands', 'Mencuci tangan', '🧴', NULL, 'I wash my hands', 'Saya mencuci tangan saya'),
('activities', 'Share toys', 'Berbagi mainan', '🧸', NULL, 'I share my toys', 'Saya berbagi mainan saya'),
('activities', 'Help friend', 'Membantu teman', '🤝', NULL, 'I help my friend', 'Saya membantu teman saya'),
('activities', 'Clean up', 'Membersihkan', '🧹', NULL, 'I clean up toys', 'Saya membereskan mainan'),
('activities', 'Throw trash', 'Membuang sampah', '🗑️', NULL, 'I throw the trash', 'Saya membuang sampah'),
('activities', 'Say thanks', 'Mengucapkan terima kasih', '🙏', NULL, 'I always say thanks', 'Saya selalu mengucapkan terima kasih'),
('activities', 'Say please', 'Mengucapkan tolong', '🥺', NULL, 'I always say please', 'Saya selalu bilang tolong'),
('activities', 'Go home', 'Pulang ke rumah', '🏡', NULL, 'I go home now', 'Saya pulang ke rumah sekarang'),
('activities', 'Take off shoes', 'Melepas sepatu', '👞', NULL, 'I take off shoes', 'Saya melepas sepatu'),
('activities', 'Change clothes', 'Ganti baju', '👖', NULL, 'I change my clothes', 'Saya mengganti pakaian saya'),
('activities', 'Wash feet', 'Cuci kaki', '🦶', NULL, 'I wash my feet', 'Saya mencuci kaki saya'),
('activities', 'Rest', 'Istirahat', '🛋️', NULL, 'I rest for awhile', 'Saya beristirahat sejenak'),
('activities', 'Take a nap', 'Tidur siang', '😴', NULL, 'I take a nap', 'Saya tidur siang'),
('activities', 'Wake up nap', 'Bangun tidur siang', '🥱', NULL, 'I wake up now', 'Saya bangun sekarang'),
('activities', 'Eat a snack', 'Makan camilan', '🍪', NULL, 'I eat a snack', 'Saya memakan camilan'),
('activities', 'Watch TV', 'Menonton TV', '📺', NULL, 'I watch fun TV', 'Saya menonton TV yang seru'),
('activities', 'Play games', 'Bermain game', '🎮', NULL, 'I play video games', 'Saya bermain video game'),
('activities', 'Read story', 'Membaca cerita', '🦸', NULL, 'I read a story', 'Saya membaca cerita'),
('activities', 'Ride bike', 'Naik sepeda', '🚲', NULL, 'I ride my bike', 'Saya mengendarai sepeda saya'),
('activities', 'Play in park', 'Bermain di taman', '🏞️', NULL, 'I play in park', 'Saya bermain di taman'),
('activities', 'Play with pet', 'Bermain dengan hewan peliharaan', '🐕', NULL, 'I play with dog', 'Saya bermain dengan anjing'),
('activities', 'Feed the dog', 'Memberi makan anjing', '🍖', NULL, 'I feed the dog', 'Saya memberi makan anjing'),
('activities', 'Feed the cat', 'Memberi makan kucing', '🐟', NULL, 'I feed the cat', 'Saya memberi makan kucing'),
('activities', 'Water plants', 'Menyiram tanaman', '🌱', NULL, 'I water the plants', 'Saya menyiram tanaman'),
('activities', 'Sweep floor', 'Menyapu lantai', '🧹', NULL, 'I sweep the floor', 'Saya menyapu lantai'),
('activities', 'Help mom', 'Membantu ibu', '👩‍👦', NULL, 'I help my mom', 'Saya membantu ibu saya'),
('activities', 'Help dad', 'Membantu ayah', '👨‍👦', NULL, 'I help my dad', 'Saya membantu ayah saya'),
('activities', 'Do homework', 'Mengerjakan PR', '📝', NULL, 'I do my homework', 'Saya mengerjakan PR saya'),
('activities', 'Study math', 'Belajar matematika', '➕', NULL, 'I study math today', 'Saya belajar matematika hari ini'),
('activities', 'Study science', 'Belajar sains', '🔬', NULL, 'I study science today', 'Saya belajar sains hari ini'),
('activities', 'Learn English', 'Belajar bahasa Inggris', '🔤', NULL, 'I learn English fast', 'Saya belajar bahasa Inggris dengan cepat'),
('activities', 'Play piano', 'Bermain piano', '🎹', NULL, 'I play the piano', 'Saya bermain piano'),
('activities', 'Play guitar', 'Bermain gitar', '🎸', NULL, 'I play the guitar', 'Saya bermain gitar'),
('activities', 'Listen music', 'Mendengarkan musik', '🎧', NULL, 'I listen to music', 'Saya mendengarkan musik'),
('activities', 'Exercise', 'Olahraga', '💪', NULL, 'I exercise every day', 'Saya berolahraga setiap hari'),
('activities', 'Swim', 'Berenang', '🏊', NULL, 'I swim in pool', 'Saya berenang di kolam'),
('activities', 'Play football', 'Bermain sepak bola', '⚽', NULL, 'I play football well', 'Saya bermain sepak bola dengan baik'),
('activities', 'Play basketball', 'Bermain bola basket', '🏀', NULL, 'I play basketball well', 'Saya bermain bola basket dengan baik'),
('activities', 'Eat dinner', 'Makan malam', '🍲', NULL, 'I eat my dinner', 'Saya makan malam'),
('activities', 'Drink juice', 'Minum jus', '🧃', NULL, 'I drink orange juice', 'Saya minum jus jeruk'),
('activities', 'Wash dishes', 'Mencuci piring', '🍽️', NULL, 'I wash the dishes', 'Saya mencuci piring'),
('activities', 'Wipe table', 'Mengelap meja', '🧽', NULL, 'I wipe the table', 'Saya mengelap meja'),
('activities', 'Take out trash', 'Membuang sampah', '🗑️', NULL, 'I take out trash', 'Saya membuang sampah'),
('activities', 'Brush hair', 'Menyisir rambut', '💇', NULL, 'I brush my hair', 'Saya menyisir rambut'),
('activities', 'Take a bath', 'Mandi rendam', '🛀', NULL, 'I take a bath', 'Saya mandi berendam'),
('activities', 'Dry hair', 'Mengeringkan rambut', '🧖', NULL, 'I dry my hair', 'Saya mengeringkan rambut saya'),
('activities', 'Wear pajamas', 'Memakai piyama', '👘', NULL, 'I wear my pajamas', 'Saya memakai piyama saya'),
('activities', 'Look at moon', 'Melihat bulan', '🌕', NULL, 'I look at moon', 'Saya melihat bulan'),
('activities', 'Look at stars', 'Melihat bintang', '⭐', NULL, 'I see the stars', 'Saya melihat bintang'),
('activities', 'Close window', 'Menutup jendela', '🪟', NULL, 'I close the window', 'Saya menutup jendela'),
('activities', 'Turn off lights', 'Mematikan lampu', '💡', NULL, 'I turn off lights', 'Saya mematikan lampu'),
('activities', 'Say goodnight', 'Mengucapkan selamat malam', '🌛', NULL, 'I say goodnight now', 'Saya mengucapkan selamat malam sekarang'),
('activities', 'Hug mom', 'Memeluk ibu', '🤗', NULL, 'I hug my mom', 'Saya memeluk ibu saya'),
('activities', 'Kiss dad', 'Mencium ayah', '💋', NULL, 'I kiss my dad', 'Saya mencium ayah saya'),
('activities', 'Go to bed', 'Pergi tidur', '🛏️', NULL, 'I go to bed', 'Saya pergi tidur'),
('activities', 'Sleep', 'Tidur', '💤', NULL, 'I sleep very well', 'Saya tidur sangat lelap'),
('activities', 'Dream', 'Bermimpi', '💭', NULL, 'I have a dream', 'Saya mempunyai mimpi'),
('activities', 'Make bed', 'Merapikan tempat tidur', '🛌', NULL, 'I make my bed', 'Saya merapikan tempat tidur saya'),
('activities', 'Check time', 'Mengecek waktu', '⌚', NULL, 'I check the time', 'Saya mengecek waktu'),
('activities', 'Wait for bus', 'Menunggu bus', '🚏', NULL, 'I wait for bus', 'Saya menunggu bus'),
('activities', 'Cross street', 'Menyeberang jalan', '🚶', NULL, 'I cross the street', 'Saya menyeberang jalan'),
('activities', 'Look left', 'Menengok kiri', '👀', NULL, 'I look left now', 'Saya menengok kiri sekarang'),
('activities', 'Use toilet', 'Menggunakan toilet', '🚽', NULL, 'I use the toilet', 'Saya menggunakan toilet'),
('activities', 'Flush toilet', 'Menyiram toilet', '🚽', NULL, 'I flush the toilet', 'Saya menyiram toilet'),
('activities', 'Tie shoelaces', 'Mengikat tali sepatu', '👟', NULL, 'I tie my shoelaces', 'Saya mengikat tali sepatu saya'),
('activities', 'Button shirt', 'Mengkancingkan kemeja', '👔', NULL, 'I button my shirt', 'Saya mengkancingkan kemeja saya'),
('activities', 'Zip jacket', 'Meresleting jaket', '🧥', NULL, 'I zip my jacket', 'Saya meresleting jaket saya'),
('activities', 'Put on hat', 'Memakai topi', '🧢', NULL, 'I put on hat', 'Saya memakai topi');
